version: 2.1

jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:  
                name: Inject build date
                command: ./scripts/inject-build-date.sh
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # Test the source code
            - run:
                name: Testing
                command: npm run test -- --watch=false
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: npm run build -- --prod
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist


deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        parameters:
            version:
                type: string
                default: ""
        steps:
            - checkout
            - restore_cache:
                key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

            - run:
                name: Deploy
                command: |
                    mkdir gh-pages-branch
                    cd gh-pages-branch
                    git config --global user.name "CircleCI"
                    git init
                    echo adding remote
                    git remote add --fetch origin https://$GH_TOKEN@github.com/torbjorv/shadebobs.git > /dev/null 2>&1
                    echo checking out
                    git checkout gh-pages
                    echo running deployment
                    ./versions/deploy.sh << parameters.version >> ../dist https://torbjorv.github.io/shadebobs/ https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID https://github.com/torbjorv/shadebobs/commit/$CIRCLE_SHA1
                    cd ..
                    rm -rf gh-pages-branch        

workflows:
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master

            # Deploy to gh-pages/builds/latest
            - deploy:
                name: deploy-dev
                requires:
                    - build
                filters:
                    branches:
                        only: master
                version: "$CIRCLE_BUILD_NUM"

            # Promoting a given build to 'prod' requires manual approval
            - approve:
                type: approval
                requires:
                    - build
                filters:
                    branches:
                        only: master

            # Deploys to gh-pages branch root level
            - deploy:
                name: deploy-prod
                requires:
                    - approve
                filters:
                    branches:
                        only: master
                version: prod            